name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Conrad Großer <grosserconrad@gmail.com>

inputs:
  commit_message:
    description: Commit message
    required: false
    default: 'Prettified Code!'
  commit_options:
    description: Commit options
    required: false
  file_pattern:
    description: File pattern used for `git add`
    required: false
    default: '*'
  prettier_options:
    description: Options for the `prettier` command
    required: false
    default: '--write **/*.js'
  branch:
    description: Branch which the changes are merged to
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'award'
  color: 'green'
